### ISSUE TITLE
Re: efficiency

### ISSUE THREAD

**Issue by smilinazzo** [pawelkosmicki/event-router#1]
https://github.com/pawelkosmicki/event-router/blob/8acf8787c3cdc5181b7bf067e84f8f5741f8c8df/test/test.js#L32

Here you are:
- reading two large files
- merging the 2 into a larger file
- then reading the large merged file
- then writing the sorted events to two more files

Can you try to  implement a more efficient way to accomplish this?

What happens if the event count increases significantly in the future? Does the data need to be sorted?

**Comment by pawelkosmicki** [comment]
Thank you for your feedback. It was very helpful!

I completely refactored the test. I decided to use hash algorithm to increase the efficiency and not to compare the content of the files.

Fixed in:
https://github.com/pawelkosmicki/event-router/commit/d6cf019b3bcd053b0789e93ad4a830e99c70ea1a
