### ISSUE TITLE
Re: excess logging?

### ISSUE THREAD

**Issue by smilinazzo** [pawelkosmicki/event-router#2]
https://github.com/pawelkosmicki/event-router/blob/8acf8787c3cdc5181b7bf067e84f8f5741f8c8df/test/test.js#L85

When/if this fails, you are logging more that 1million lines.

**Comment by pawelkosmicki** [comment]
Fixed in:
https://github.com/pawelkosmicki/event-router/commit/d6cf019b3bcd053b0789e93ad4a830e99c70ea1a
