### ISSUE TITLE
Re: tests

### ISSUE THREAD

**Issue by smilinazzo** [pawelkosmicki/event-router#3]
https://github.com/pawelkosmicki/event-router/blob/8acf8787c3cdc5181b7bf067e84f8f5741f8c8df/test/test.js#L77
https://github.com/pawelkosmicki/event-router/blob/8acf8787c3cdc5181b7bf067e84f8f5741f8c8df/test/test.js#L88

What does the result of the second test tell you that the result of the first test doesn't?

**Comment by pawelkosmicki** [comment]
It was added to show that different types of tests can be used depending on the acceptance criteria. 

Fixed in:
https://github.com/pawelkosmicki/event-router/commit/d6cf019b3bcd053b0789e93ad4a830e99c70ea1a
